### ISSUE TITLE
Android SDK article

### ISSUE THREAD

**Issue by just1and0** [OrthoHQ/android-ortho#3]

**Comment by aniekan12** [comment]
@just1and0  https://medium.com/@ani_88195/how-to-integrate-ortho-in-your-android-app-e9cf746d36bb

**Comment by just1and0** [comment]
@aniekan12 can you submit this to organisation on medium ?

**Comment by just1and0** [comment]
looks good.

**Comment by just1and0** [comment]
@aniekan12 awesome work, can you submit this to organisation on medium ?
